In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Rikitea,-23.12,-134.97,75.92,68,65,5.17,PF,2020-05-09 05:27:13
1,1,Naze,28.37,129.48,77.00,78,40,12.75,JP,2020-05-09 05:27:13
2,2,Albany,42.60,-73.97,34.00,68,100,1.01,US,2020-05-09 05:27:13
3,3,Bluff,-46.60,168.33,58.60,78,3,5.91,NZ,2020-05-09 05:27:14
4,4,Tiksi,71.69,128.87,22.03,96,100,9.46,RU,2020-05-09 05:27:14

In [3]:
# Check data types
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp],
                                 dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 90

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Rikitea,-23.12,-134.97,75.92,68,65,5.17,PF,2020-05-09 05:27:13
1,1,Naze,28.37,129.48,77.00,78,40,12.75,JP,2020-05-09 05:27:13
3,3,Bluff,-46.60,168.33,58.60,78,3,5.91,NZ,2020-05-09 05:27:14
5,5,Awbari,26.59,12.78,73.87,27,82,10.74,LY,2020-05-09 05:27:14
6,6,Hobart,-42.88,147.33,55.40,58,75,6.93,AU,2020-05-09 05:23:25
7,7,Behbahan,30.60,50.24,87.80,20,40,2.24,IR,2020-05-09 05:25:07
8,8,Codrington,-38.27,141.97,52.29,63,96,23.53,AU,2020-05-09 05:27:14
9,9,Chabahar,25.29,60.64,86.16,57,0,4.09,IR,2020-05-09 05:27:15
11,11,Chemainus,48.92,-123.72,61.00,51,5,2.24,CA,2020-05-09 05:22:31
12,12,Kieta,-6.22,155.63,84.36,70,14,5.14,PG,2020-05-09 05:27:15

In [12]:
# Checking for null values
preferred_cities_df.count()

City_ID       418
City          418
Lat           418
Lng           418
Max Temp      418
Humidity      418
Cloudiness    418
Wind Speed    418
Country       414
Date          418
dtype: int64

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp    Lat     Lng Hotel Name
0      Rikitea      PF     75.92 -23.12 -134.97
1         Naze      JP     77.00  28.37  129.48
3        Bluff      NZ     58.60 -46.60  168.33
5       Awbari      LY     73.87  26.59   12.78
6       Hobart      AU     55.40 -42.88  147.33
7     Behbahan      IR     87.80  30.60   50.24
8   Codrington      AU     52.29 -38.27  141.97
9     Chabahar      IR     86.16  25.29   60.64
11   Chemainus      CA     61.00  48.92 -123.72
12       Kieta      PG     84.36  -6.22  155.63

In [14]:
# Set parameters to search for a hotel.
params = {"radius": 5000,
          "type": "lodging",
          "key": g_key
         }

In [15]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print('-----Hotel Found-----')
    except (IndexError):
        print("-----Hotel Not Found-----")

-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----

-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Found-----
-----Hotel Not Found-----
-----Hotel Found-----

In [16]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Rikitea,PF,75.92,-23.12,-134.97,Pension Maro'i
1,Naze,JP,77.00,28.37,129.48,奄美ポートタワーホテル
3,Bluff,NZ,58.60,-46.60,168.33,Bluff Homestead - Guesthouse & Campervan Park
5,Awbari,LY,73.87,26.59,12.78,فندق أوباري
6,Hobart,AU,55.40,-42.88,147.33,St Ives Apartments
7,Behbahan,IR,87.80,30.60,50.24,Esteghlal Hotel
8,Codrington,AU,52.29,-38.27,141.97,Codrington Gardens Bed And Breakfast
9,Chabahar,IR,86.16,25.29,60.64,هتل گدروشیا
11,Chemainus,CA,61.00,48.92,-123.72,Fuller Lake Motel
12,Kieta,PG,84.36,-6.22,155.63,

In [17]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))